# Generated by Django 5.0.7 on 2024-07-28 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autism_predictor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='Users',
        ),
    ]
