# Generated by Django 5.0.7 on 2024-07-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autism_predictor', '0002_alter_users_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='longquestions',
            name='category',
            field=models.CharField(choices=[('social_orientating_and_receptive_communication', 'Social orientating and receptive communication'), ('expressive_communication', 'Expressive communication'), ('sensory_processing', 'Sensory processing'), ('repetitive_behaviour', 'Repetitive behaviour'), ('imitation', 'Imitation'), ('social_and_affective_engagement', 'Social and affective engagement'), ('reactivity', 'Reactivity'), ('no category', 'No category')], max_length=255),
        ),
        migrations.AlterField(
            model_name='shortquestions',
            name='category',
            field=models.CharField(choices=[('social_orientating_and_receptive_communication', 'Social orientating and receptive communication'), ('expressive_communication', 'Expressive communication'), ('sensory_processing', 'Sensory processing'), ('repetitive_behaviour', 'Repetitive behaviour'), ('imitation', 'Imitation'), ('social_and_affective_engagement', 'Social and affective engagement'), ('reactivity', 'Reactivity'), ('no category', 'No category')], max_length=255),
        ),
    ]
